// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu1afXFpMcCOFBkNS25SWBx4osRp86-Pw',
    appId: '1:719019166826:android:abf8a61007932d0b650e13',
    messagingSenderId: '719019166826',
    projectId: 'reroll-a2a74',
    storageBucket: 'reroll-a2a74.appspot.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPEqacMofAi0u7riJvfIGF5CUCshIkeY',
    appId: '1:719019166826:ios:7433d0ebadd69497650e13',
    messagingSenderId: '719019166826',
    projectId: 'reroll-a2a74',
    storageBucket: 'reroll-a2a74.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84ErokkCJbhZWO_ib7x3fGNkkyuhDHI8',
    appId: '1:719019166826:web:16f0d6bcb856aec8650e13',
    messagingSenderId: '719019166826',
    projectId: 'reroll-a2a74',
    authDomain: 'reroll-a2a74.firebaseapp.com',
    storageBucket: 'reroll-a2a74.firebasestorage.app',
    measurementId: 'G-2X7N5Z6RWS',
  );

}